[package]
name = "squawkbox"
authors = ["benny b <ben@bitcoinbay.foundation>"]
version = "0.1.0"
edition = "2024"
description = "DLC contract communication over nostr."
license = "MIT"

[dependencies]
